name: Run Backend and Tests

on:
  workflow_dispatch:

jobs:
  run-backend-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install backend dependencies
        working-directory: crud_clientes_node/backend
        run: |
          npm install
          npm install swagger-jsdoc

      - name: Verify installed packages
        working-directory: crud_clientes_node/backend
        run: npm list

      - name: Start Backend
        working-directory: crud_clientes_node/backend
        run: node app.js

      - name: Wait for Backend
        run: sleep 5

      - name: Run Tests
        working-directory: crud_clientes_test
        run: npx jest test
