name: 'Execucao manual'

# Permite que o fluxo seja executado manualmente
on:
  workflow_dispatch:

jobs:
  run-backend-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd crud_clientes_node
          npm install

      - name: Start Backend
        run: |
          cd crud_clientes_node/backend
          nohup node app.js & # 'nohup' e '&' mantém o processo rodando em segundo plano

      - name: Wait for Backend
        run: sleep 5

      - name: Run Tests
        run: |
          cd crud_clientes_test
          npx jest test
