name: Run Backend and Tests

on:
  workflow_dispatch:

jobs:
  run-backend-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install backend dependencies
        working-directory: crud_clientes_node/backend
        run: |
          npm install
          npm install swagger-jsdoc swagger-ui-express

      - name: Start Backend
        working-directory: crud_clientes_node/backend
        run: |
          nohup node app.js &

      - name: Wait for Backend
        run: sleep 5

      - name: Install test dependencies
        working-directory: crud_clientes_test
        run: |
          npm install
          npm install jest jest-stare jest-html-reporter

      - name: Run Tests
        working-directory: crud_clientes_test
        run: npx jest test
      
       - name: Generate Test Report
        working-directory: crud_clientes_test
        run: |
          mkdir -p jest-stare
          cp jest-stare/report.html ./jest-stare/report.html
